# Generated by Django 5.2.15 on 2026-08-19 05:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='phase_goal',
            field=models.TextField(blank=True, null=True, verbose_name='阶段目标'),
        ),
        migrations.AddField(
            model_name='issue',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='完成百分比'),
        ),
        migrations.AddField(
            model_name='issue',
            name='risk',
            field=models.TextField(blank=True, null=True, verbose_name='风险'),
        ),
        migrations.AddField(
            model_name='issue',
            name='version_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目版本名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('标品', '标品'), ('立项', '立项'), ('能力', '能力'), ('其他', '其他'), ('项目', '项目'), ('演示', '演示'), ('专项', '专项')], max_length=50, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='结论情况'),
        ),
        migrations.AddField(
            model_name='project',
            name='demand_background',
            field=models.TextField(blank=True, null=True, verbose_name='需求背景/简述'),
        ),
        migrations.AddField(
            model_name='project',
            name='demand_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求提出时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='demand_proposer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='需求提出人'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估利润'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估收入'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_privatized',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=10, null=True, verbose_name='是否私有化'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_notes',
            field=models.TextField(blank=True, null=True, verbose_name='重点信息备注'),
        ),
        migrations.AddField(
            model_name='project',
            name='lanes_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='路数'),
        ),
        migrations.AddField(
            model_name='project',
            name='okr',
            field=models.CharField(blank=True, choices=[('一季度', '一季度'), ('二季度', '二季度'), ('三季度', '三季度'), ('四季度', '四季度')], max_length=50, null=True, verbose_name='OKR'),
        ),
        migrations.AddField(
            model_name='project',
            name='settlement_status',
            field=models.CharField(blank=True, choices=[('报价中', '报价中'), ('结算中', '结算中'), ('推进中', '推进中'), ('未报价', '未报价'), ('已结算', '已结算')], max_length=20, null=True, verbose_name='结算情况'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='来源部门'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_category',
            field=models.CharField(blank=True, choices=[('保存量', '保存量'), ('建能力', '建能力'), ('求拓展', '求拓展')], max_length=50, null=True, verbose_name='工作分类'),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='行业名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='行业描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='db.industry', verbose_name='行业'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='里程碑描述')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'db_table': 'milestones',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.milestone', verbose_name='里程碑'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='industry_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
    ]
