# Generated by Django 5.2.15 on 2026-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_phase_goal_issue_progress_issue_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='结论情况'),
        ),
        migrations.AddField(
            model_name='issue',
            name='demand_background',
            field=models.TextField(blank=True, null=True, verbose_name='需求背景/简述'),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估利润'),
        ),
        migrations.AddField(
            model_name='issue',
            name='estimated_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估收入'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_privatized',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=10, null=True, verbose_name='是否私有化'),
        ),
        migrations.AddField(
            model_name='issue',
            name='key_notes',
            field=models.TextField(blank=True, null=True, verbose_name='重点信息备注'),
        ),
        migrations.AddField(
            model_name='issue',
            name='lanes_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='路数'),
        ),
        migrations.AddField(
            model_name='issue',
            name='okr',
            field=models.CharField(blank=True, choices=[('一季度', '一季度'), ('二季度', '二季度'), ('三季度', '三季度'), ('四季度', '四季度')], max_length=50, null=True, verbose_name='OKR'),
        ),
        migrations.AddField(
            model_name='issue',
            name='settlement_status',
            field=models.CharField(blank=True, choices=[('报价中', '报价中'), ('结算中', '结算中'), ('推进中', '推进中'), ('未报价', '未报价'), ('已结算', '已结算')], max_length=20, null=True, verbose_name='结算情况'),
        ),
        migrations.AddField(
            model_name='issue',
            name='work_category',
            field=models.CharField(blank=True, choices=[('保存量', '保存量'), ('建能力', '建能力'), ('求拓展', '求拓展')], max_length=50, null=True, verbose_name='工作分类'),
        ),
    ]
