# Generated by Django 5.2.15 on 2026-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_add_subrequirement_fields_to_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deliverables',
            field=models.TextField(blank=True, null=True, verbose_name='输出物'),
        ),
    ]
