# Generated by Django 5.2.15 on 2026-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_add_deliverables_to_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='has_phases',
            field=models.BooleanField(default=False, verbose_name='是否多阶段'),
        ),
    ]
