# Generated by Django 5.2.15 on 2026-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_add_has_phases_to_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lanes_count',
            field=models.FloatField(blank=True, null=True, verbose_name='路数（万路）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lanes_count',
            field=models.FloatField(blank=True, null=True, verbose_name='路数（万路）'),
        ),
    ]
