# Generated by Django 5.2.15 on 2026-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_issue_task_log_alter_issuemilestoneitem_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
