# Generated by Django 5.2.15 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_issue_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueassignee',
            name='assignee_role',
            field=models.CharField(blank=True, choices=[('产品', '产品'), ('研发', '研发')], help_text='负责人分工：产品 / 研发 / 无', max_length=10, null=True, verbose_name='负责人分工'),
        ),
    ]