# Generated by Django 5.2.15 on 2026-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_issuehidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuehidden',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
    ]
