FROM python:3.12.5-alpine AS backend

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple/
ENV PIP_DEFAULT_TIMEOUT=300
ENV INSTANCE_CHANGELOG_URL https://sites.plane.so/pages/691ef037bcfe416a902e48cb55f59891/

# 切换 Alpine 包管理器源为阿里云镜像
RUN sed -i 's@dl-cdn.alpinelinux.org@mirrors.aliyun.com@g' /etc/apk/repositories

RUN apk --no-cache add \
    "bash~=5.2" \
    "libpq" \
    "libxslt" \
    "nodejs-current" \
    "xmlsec" \
    "libffi-dev" \
    "bash~=5.2" \
    "g++" \
    "gcc" \
    "cargo" \
    "git" \
    "make" \
    "postgresql-dev" \
    "libc-dev" \
    "linux-headers"

WORKDIR /code

COPY requirements.txt ./requirements.txt
ADD requirements ./requirements

# Install the local development settings
RUN pip install --no-cache-dir -r requirements/local.txt --compile


COPY . .

RUN mkdir -p /code/plane/logs
RUN chmod -R +x /code/bin
RUN chmod -R 777 /code


# Expose container port and run entry point script
EXPOSE 8000

CMD [ "./bin/docker-entrypoint-api-local.sh" ]

